[package]
name = "tiled-parser"
version = "0.1.2"
authors = ["Martin Lindhe <martin@ubique.se>"]
license = "MIT"
description = "Tiled JSON deserializer and serializer"
repository = "https://github.com/martinlindhe/tiled-parser"

[dependencies]
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
